name: q

on: ['push']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: postgresql dev
      run: sudo apt-get install postgresql-server-dev-12  -y -qq
       
    - name: Makefile
      run: make
